### ISSUE TITLE
Uncaught Error on class not found

### ISSUE THREAD

**Issue by shelane** [docksal/blt-docksal#9]
The Behat command has moved with the update acquia-blt repo. The BehatDocksalCommand needs updating.

**Comment by shelane** [comment]
When running installation of BLT, this error is generated:

```
Fatal error: Uncaught Error: Class "Acquia\Blt\Robo\Commands\Tests\BehatCommand" not found in /var/www/src/Blt/Plugin/Commands/BehatDocksalCommand.php:7
Stack trace:
#0 /var/www/vendor/composer/ClassLoader.php(571): include()
#1 /var/www/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/var/www/vendor...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Docksal\\BltDock...')
#3 /var/www/vendor/consolidation/robo/src/Runner.php(374): class_exists('Docksal\\BltDock...')
#4 /var/www/vendor/consolidation/robo/src/Runner.php(346): Robo\Runner->instantiateCommandClass('Docksal\\BltDock...')
#5 /var/www/vendor/consolidation/robo/src/Runner.php(319): Robo\Runner->registerCommandClass(Object(Acquia\Blt\Robo\Application), 'Docksal\\BltDock...')
#6 /var/www/vendor/consolidation/robo/src/Runner.php(279): Robo\Runner->registerCommandClasses(Object(Acquia\Blt\Robo\Application), Array)
#7 /var/www/vendor/acquia/blt/src/Robo/Blt.php(264): Robo\Runner->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Acquia\Blt\Robo\Application), Array)
#8 /var/www/vendor/acquia/blt/bin/blt-robo-run.php(35): Acquia\Blt\Robo\Blt->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/vendor/acquia/blt/bin/blt-robo.php(15): require_once('/var/www/vendor...')
#10 /var/www/vendor/acquia/blt/bin/blt(11): require_once('/var/www/vendor...')
#11 {main}
  thrown in /var/www/src/Blt/Plugin/Commands/BehatDocksalCommand.php on line 7
PHP Fatal error:  Uncaught Error: Class "Acquia\Blt\Robo\Commands\Tests\BehatCommand" not found in /var/www/src/Blt/Plugin/Commands/BehatDocksalCommand.php:7
Stack trace:
#0 /var/www/vendor/composer/ClassLoader.php(571): include()
#1 /var/www/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/var/www/vendor...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Docksal\\BltDock...')
#3 /var/www/vendor/consolidation/robo/src/Runner.php(374): class_exists('Docksal\\BltDock...')
#4 /var/www/vendor/consolidation/robo/src/Runner.php(346): Robo\Runner->instantiateCommandClass('Docksal\\BltDock...')
#5 /var/www/vendor/consolidation/robo/src/Runner.php(319): Robo\Runner->registerCommandClass(Object(Acquia\Blt\Robo\Application), 'Docksal\\BltDock...')
#6 /var/www/vendor/consolidation/robo/src/Runner.php(279): Robo\Runner->registerCommandClasses(Object(Acquia\Blt\Robo\Application), Array)
#7 /var/www/vendor/acquia/blt/src/Robo/Blt.php(264): Robo\Runner->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Acquia\Blt\Robo\Application), Array)
#8 /var/www/vendor/acquia/blt/bin/blt-robo-run.php(35): Acquia\Blt\Robo\Blt->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/vendor/acquia/blt/bin/blt-robo.php(15): require_once('/var/www/vendor...')
#10 /var/www/vendor/acquia/blt/bin/blt(11): require_once('/var/www/vendor...')
#11 {main}
  thrown in /var/www/src/Blt/Plugin/Commands/BehatDocksalCommand.php on line 7
BLT installation failed! Please execute /var/www/vendor/acquia/blt/bin/blt internal:add-to-project --ansi -n --verbose to debug the issue.

In Plugin.php line 165:
                                     
  Installation aborted due to error  
                                     
```
